version: '2'
services:
  mysql:
    image: ilopmar/mufly-mysql:5.5.53
    environment:
      - "MYSQL_DATABASE=mufly"
      - "MYSQL_USER=mufly"
      - "MYSQL_PASSWORD=mufly"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
  tomcat:
    image: ilopmar/mufly-tomcat:6.0.47-jre7
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./tomcat:/usr/local/tomcat/webapps"
    ports:
      - "8080:8080"
